import type {
  SlashCommandSubcommandBuilder,
  ChatInputCommandInteraction,
  AutocompleteInteraction,
  ButtonInteraction,
  ModalSubmitInteraction,
  AnySelectMenuInteraction,
  StringSelectMenuInteraction,
  EmbedBuilder,
} from 'discord.js';

/** A single page generated by a paginator */
export interface PaginatorPage {
  /** The embed for this page */
  embed: EmbedBuilder;
  /** Total number of pages available */
  totalPages: number;
}

/** Command definition — each .ts file in a category folder exports this */
export interface Command {
  /** Subcommand definition using discord.js built-in builder */
  data: SlashCommandSubcommandBuilder;
  /** Main command execution handler */
  execute: (interaction: ChatInputCommandInteraction) => Promise<void>;
  /** Optional button interaction handlers, keyed by action name */
  buttons?: Record<string, (interaction: ButtonInteraction, args: string[]) => Promise<void>>;
  /** Optional modal submission handlers, keyed by action name */
  modals?: Record<string, (interaction: ModalSubmitInteraction, args: string[]) => Promise<void>>;
  /** Optional select menu handlers, keyed by action name — accepts every select type (string, user, role, mentionable, channel) */
  selectMenus?: Record<string, (interaction: AnySelectMenuInteraction, args: string[]) => Promise<void>>;
  /** Optional paginator — generates a single page on demand (for restart-safe pagination) */
  paginate?: (page: number, interaction: ButtonInteraction) => Promise<PaginatorPage>;
  /** Optional managed select menu handler — called when a StringSelectMenu interaction is received */
  select?: (
    action: string,
    values: string[],
    args: string[],
    interaction: StringSelectMenuInteraction
  ) => Promise<void>;
  /** Optional autocomplete handler for string options with autocomplete enabled */
  autocomplete?: (interaction: AutocompleteInteraction) => Promise<void>;
}

/** Optional per-category configuration — exported from a `_category.ts` file in the category folder */
export interface CategoryConfig {
  /** When true, the category is registered with DM usage disabled and guarded at runtime */
  guildOnly?: boolean;
  /** Permissions the bot must have — checked at runtime before command execution */
  botPermissions?: bigint[];
  /** Combined permission bitfield required from the invoking member (hides command in Discord UI) */
  defaultMemberPermissions?: bigint;
}

/** What the command loader produces per category */
export interface CategoryCommands {
  /** Category folder name (becomes the slash command group name) */
  name: string;
  /** Map of subcommand name to Command definition */
  commands: Map<string, Command>;
}

/** Result of parsing a structured customId */
export interface ParsedCustomId {
  /** Category name (first segment) */
  category: string;
  /** Command/subcommand name (second segment) */
  command: string;
  /** Action identifier (third segment) */
  action: string;
  /** Additional arguments (remaining segments) */
  args: string[];
}
