/**
 * AI-personalized daily cards and feedback compression, via OpenCode Go.
 *
 * The feedback loop: submissions/Inc-Dec requests are compressed into short
 * summaries, persisted per user+problem, and re-injected as prompt context the
 * next time that user's daily card is generated. The model decides the
 * difficulty tier — there is no explicit scheduling algorithm.
 *
 * @module services/aiPersonalizationService
 */
import type { Submission } from '@prisma/client';
import { loadEnv } from '../lib/env.js';
import { logger } from '../lib/logger.js';
import { fetchOfficialSolution, type DailyProblem } from '../lib/leetcodeApi.js';
import { htmlToMarkdown } from '../utils/htmlToMarkdown.js';

const OPENCODE_GO_CHAT_URL = 'https://opencode.ai/zen/go/v1/chat/completions';

/** How long to wait for the AI provider before giving up (prevents the cron tick from hanging). */
const FETCH_TIMEOUT_MS = 10_000;

/** How much of a user's history is handed to the model per generation. */
const MAX_HISTORY_ENTRIES = 10;

/** Maximum compressed-summary length the model may return before we fall back. */
const MAX_SUMMARY_LENGTH = 240;

export const DIFFICULTY_TIERS = ['Easy', 'Medium', 'Hard'] as const;

/** A personalized daily card generated by the model. */
export interface DailyCardGeneration {
  /** Flavor blurb shown under `## Description`; the app prepends the tier emoji. */
  description: string;
  /** One of `DIFFICULTY_TIERS` — the tier the personalized variant is dialed to. */
  tier: string;
  /** Personalized problem statement (markdown). */
  instructions: string;
  /** Personalized worked examples (markdown); empty when the model omits them. */
  examples: string;
}

const GENERATION_SYSTEM_PROMPT = `You are a coding coach that personalizes one LeetCode daily problem for a single learner. You receive the original problem (statement, example test cases, hints, official solution when available) and the learner's accumulated history (compressed self-reports of past problems). Produce a personalized variant:

1. description: a 2-3 sentence flavor blurb introducing the problem. Mention the difficulty tier in words (e.g. "This Easy problem is a combination of 3 different concepts..."). Do not include a difficulty emoji; the app renders it.
2. tier: one of "Easy", "Medium" or "Hard" — the difficulty of THIS personalized variant. Stay at the learner's current difficulty (the tier implied by their most recent problems) unless the history clearly justifies a move; only move the tier when accumulated self-reported difficulty or an explicit increase/decrease request supports it. Default is inertia, not drift.
3. instructions: the problem statement rewritten for this learner — same algorithmic core, difficulty dialed per the tier, framed in the learner's context when their history or preferences suggest one. Complete enough to solve without the original statement. Markdown, at most ~1200 characters.
4. examples: 1-2 worked examples, each with Input, Output and Explanation lines, consistent with the personalized instructions. Markdown, at most ~800 characters.

Respond with STRICT JSON only, no prose before or after:
{"description": string, "tier": "Easy"|"Medium"|"Hard", "instructions": string, "examples": string}`;

const COMPRESSION_SYSTEM_PROMPT = `You compress a learner's self-reported feedback about one LeetCode problem into ONE short sentence (at most 40 words) that a personalization model will read later. Preserve the difficulty signal and any concrete algorithmic or domain detail. No markdown, no quotes, no label prefixes — just the sentence.`;

interface OpenCodeChatResponse {
  choices?: Array<{
    message?: { content?: string };
    finish_reason?: string;
  }>;
}

/**
 * One OpenCode Go chat completion, with the same guards that fixed #17.
 *
 * @postcondition Returns a trimmed non-empty completion, or `null` when the key
 *   is unset, the request/response fails, the provider returns a truncated
 *   (mid-response) completion, or the completion is empty — never throws, since
 *   this runs inside a background cron tick where a flaky third-party AI call
 *   must not block the rest of the dispatch.
 */
async function chatCompletion(
  systemPrompt: string,
  userContent: string,
  maxTokens: number
): Promise<string | null> {
  const env = loadEnv();
  if (!env.OPENCODE_API_KEY) return null;

  let res: Response;
  try {
    res = await fetch(OPENCODE_GO_CHAT_URL, {
      method: 'POST',
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: {
        Authorization: `Bearer ${env.OPENCODE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: env.OPENCODE_GO_MODEL,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userContent },
        ],
        // deepseek-v4-flash (and other Go reasoning models) count reasoning
        // tokens against max_tokens; leave headroom so the visible output isn't
        // cut off mid-response when the model reasons long.
        max_tokens: maxTokens,
      }),
    });
  } catch (error) {
    logger.warn({ error }, 'OpenCode Go request failed');
    return null;
  }

  if (!res.ok) {
    logger.warn({ status: res.status }, 'OpenCode Go request failed');
    return null;
  }

  let data: OpenCodeChatResponse;
  try {
    data = (await res.json()) as OpenCodeChatResponse;
  } catch (error) {
    logger.warn({ error }, 'OpenCode Go response was not valid JSON');
    return null;
  }
  const choice = data.choices?.[0];
  const content = choice?.message?.content?.trim();
  if (!content) return null;

  // A `length` finish_reason means the model hit the token budget mid-response
  // (reasoning models spend tokens reasoning before writing). Surfacing the
  // partial text is the bug reported in #17; treat it as a failed generation so
  // callers fall back to complete default content.
  if (choice?.finish_reason?.toLowerCase() === 'length') {
    logger.warn('OpenCode Go response truncated (finish_reason=length); using fallback content');
    return null;
  }

  return content;
}

/**
 * Build the non-personalized card content used when AI is disabled, generation
 * fails, or the user has no personalization context yet.
 *
 * @postcondition `tier` is the problem's LeetCode difficulty; `instructions` is
 *   the plain-statement markdown; `examples` is empty (the statement embeds its
 *   own examples).
 */
export function buildDefaultCardContent(problem: DailyProblem): DailyCardGeneration {
  return {
    description: "Today's LeetCode daily is up — good luck!",
    tier: problem.difficulty,
    instructions: htmlToMarkdown(problem.question),
    examples: '',
  };
}

/**
 * Generate a personalized daily card for one user.
 *
 * Hands the model the original problem, its test cases, the official solution
 * (when available), and the user's compressed history; the model rewrites the
 * statement/examples and picks the difficulty tier.
 *
 * @postcondition Returns validated `{ description, tier, instructions, examples }`,
 *   or `null` on any failure — never throws.
 */
export async function generateDailyCardContent(params: {
  prompt: string | null;
  problem: DailyProblem;
  history: Submission[];
}): Promise<DailyCardGeneration | null> {
  const { prompt, problem, history } = params;

  const solution = await fetchOfficialSolution(problem.titleSlug);
  const historyText =
    history.length === 0
      ? 'none yet — this is the learner\'s first problem.'
      : history
          .slice(0, MAX_HISTORY_ENTRIES)
          .map((entry) => `- ${entry.problemDate}: ${entry.compressedSummary}`)
          .join('\n');

  const userContent = [
    `Learner's preferences: ${prompt ?? 'none'}`,
    `Learner's history (newest first):\n${historyText}`,
    'Original problem:',
    `Title: ${problem.title}`,
    `Difficulty: ${problem.difficulty}`,
    `Statement:\n${htmlToMarkdown(problem.question)}`,
    `Example test cases:\n${problem.exampleTestcases}`,
    `Hints:\n${problem.hints.length > 0 ? problem.hints.join('\n') : 'none'}`,
    `Official solution:\n${solution ?? 'unavailable'}`,
    '',
    'Personalize the problem for this learner now.',
  ].join('\n');

  const raw = await chatCompletion(GENERATION_SYSTEM_PROMPT, userContent, 1500);
  if (!raw) return null;

  // Some models wrap JSON in code fences; tolerate that.
  const jsonText = raw.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonText) as unknown;
  } catch {
    logger.warn({ problem: problem.titleSlug }, 'OpenCode Go card generation was not valid JSON');
    return null;
  }

  const record = parsed as Record<string, unknown>;
  const description = typeof record.description === 'string' ? record.description.trim() : '';
  const tier = typeof record.tier === 'string' ? record.tier : '';
  const instructions = typeof record.instructions === 'string' ? record.instructions.trim() : '';
  const examples = typeof record.examples === 'string' ? record.examples.trim() : '';

  if (
    description.length === 0 ||
    !(DIFFICULTY_TIERS as readonly string[]).includes(tier) ||
    instructions.length === 0
  ) {
    logger.warn({ problem: problem.titleSlug }, 'OpenCode Go card generation failed validation');
    return null;
  }

  return { description, tier, instructions, examples };
}

/**
 * Compress one raw feedback event into a one-line summary for storage.
 *
 * @precondition `kind` is "submission" or "incdec" (give-ups never call the
 *   model — see `fallbackCompressedSummary`).
 * @postcondition Returns a short sentence, or `null` on any failure.
 */
export async function compressFeedback(params: {
  kind: 'submission' | 'incdec';
  rating?: string;
  adjustment?: string;
  feedbackText?: string;
  problemTitle: string;
  problemDifficulty: string;
}): Promise<string | null> {
  const { kind, rating, adjustment, feedbackText, problemTitle, problemDifficulty } = params;
  const userContent = [
    `Problem: ${problemTitle} (${problemDifficulty})`,
    kind === 'submission' ? `Self-reported difficulty: ${rating ?? 'unrated'}` : `Requested change: ${adjustment ?? 'unspecified'}`,
    `Details: ${feedbackText ?? 'none'}`,
    'Compress to one sentence.',
  ].join('\n');

  const raw = await chatCompletion(COMPRESSION_SYSTEM_PROMPT, userContent, 300);
  if (!raw) return null;

  // A summary that doesn't end in sentence-final punctuation is incomplete.
  if (!/[.!?…]$/.test(raw) || raw.length > MAX_SUMMARY_LENGTH) {
    logger.warn({ problemTitle }, 'OpenCode Go compression was incomplete; using mechanical summary');
    return null;
  }

  return raw;
}

/**
 * Mechanical summary used when the model is unavailable or its compression is
 * rejected. Also the sole path for give-ups, which carry no compressible detail.
 *
 * @postcondition Returns a deterministic one-line summary for the event.
 */
export function fallbackCompressedSummary(params: {
  kind: 'submission' | 'incdec' | 'giveup';
  rating?: string;
  adjustment?: string;
  feedbackText?: string;
  problemTitle: string;
}): string {
  switch (params.kind) {
    case 'submission':
      return `Solved ${params.problemTitle} and rated it "${params.rating ?? 'unrated'}".`;
    case 'incdec': {
      const direction = params.adjustment === 'Increase' ? 'harder' : 'easier';
      const details = params.feedbackText ? ` (${params.feedbackText})` : '';
      return `Wants the next problem ${direction}${details}.`;
    }
    case 'giveup':
      return `Gave up on ${params.problemTitle} without submitting.`;
  }
}
